name: CI Demo  # Continuous Integration Demo
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Show Hello World
        run: echo "Hello World, your CI is working!"
